resolver: lts-7.14

packages:
- '.'
- location:
    git: https://github.com/nh2/haskell-cpython.git
    commit: 669dbcfbf02e658440de945eb2e3fb26a2505845
  extra-dep: true

extra-deps:
  - data-msgpack-0.0.9
